export const STRINGS = {
  common: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    confirm: 'Confirmar',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Exitoso',
    back: 'Volver',
    noResults: 'No se encontraron resultados',
  },
  auth: {
    title: 'Panel Administrativo',
    subtitle: 'UNICEF Colombia — Libros Digitales',
    emailLabel: 'Email',
    passwordLabel: 'Contraseña',
    loginButton: 'Iniciar sesión',
    loginLoading: 'Iniciando sesión...',
    loginError: 'Email o contraseña incorrectos',
    emailPlaceholder: 'correo@ejemplo.com',
  },
  admin: {
    dashboard: 'Dashboard',
    dashboardSubtitle: 'Resumen general de la plataforma',
    publications: 'Publicaciones',
    analytics: 'Analytics',
    analyticsSubtitle: 'Estadísticas detalladas de la plataforma',
    viewPublicSite: 'Ver sitio público',
    signOut: 'Cerrar sesión',
    administrator: 'Administrador',
    addBook: 'Agregar libro',
    editBook: 'Editar libro',
    newBook: 'Nuevo libro',
    editBookSubtitle: 'Modifica los datos del libro',
    newBookSubtitle: 'Agrega un nuevo libro a la biblioteca',
    saveChanges: 'Guardar cambios',
    createBook: 'Crear libro',
    saving: 'Guardando...',
    deleteConfirm: 'Confirmar',
    deleteError: 'Error al eliminar el libro',
    booksRegistered: (n: number) => `${n} libros registrados`,
    visibleInLibrary: 'Visible en la biblioteca',
  },
  stats: {
    publishedBooks: 'Libros publicados',
    totalInteractions: 'Total interacciones',
    reads: 'Lecturas',
    downloads: 'Descargas',
    mostPopularBooks: 'Libros más populares',
    interactions: 'interacciones',
    byUserType: 'Por tipo de usuario',
    byGender: 'Por género',
    byBook: 'Por libro',
    byAgeRange: 'Por rango de edad',
    recentActivity: 'Actividad reciente',
    unspecified: 'Sin especificar',
  },
  survey: {
    readTitle: '¡Vamos a leer!',
    downloadTitle: '¡Descarga tu libro!',
    subtitle: 'Cuéntanos un poco sobre ti antes de continuar',
    whoAreYou: '¿Quién eres?',
    ageRangeLabel: 'Rango de edad',
    genderLabel: '¿Cuál es tu género?',
    readNow: 'Leer ahora',
    downloadNow: 'Descargar ahora',
    roles: {
      nina: 'Niña',
      nino: 'Niño',
      familia: 'Familia',
      docente: 'Docente',
      estudiante: 'Estudiante',
      otro: 'Otro',
    },
    ageRanges: {
      '0-5': { label: '0–5 años', sublabel: 'Primera infancia' },
      '6-10': { label: '6–10 años', sublabel: 'Infancia' },
      '11+': { label: '11+ años', sublabel: 'Adolescencia / Adulto' },
    },
    genders: {
      femenino: 'Femenino',
      masculino: 'Masculino',
      otro: 'Otro',
      prefiero_no_decir: 'Prefiero no decir',
    },
  },
  table: {
    book: 'Libro',
    categories: 'Categorías',
    year: 'Año',
    status: 'Estado',
    actions: 'Acciones',
    role: 'Rol',
    gender: 'Género',
    action: 'Acción',
    date: 'Fecha',
    visible: 'Visible',
    hidden: 'Oculto',
  },
  footer: {
    navigation: 'Navegación',
    home: 'Inicio',
    library: 'Biblioteca',
    aboutProject: 'Sobre el proyecto',
    aboutDescription: 'Libros digitales accesibles diseñados para promover la lectura y el aprendizaje de todos los niños y niñas de Colombia.',
    supportedBy: 'Con el apoyo de',
    madeWith: 'Hecho con',
    forChildren: 'para la infancia colombiana',
    allRightsReserved: 'Todos los derechos reservados',
  },
} as const;
